/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Teacher.TeacherControl;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import Secretary.SecretaryControl;
import static newatomicstudent.functions.*;

/**
 *
 * @author mahmo
 */
public class Login extends javax.swing.JFrame {

    Connection con = general_connection();
    Connection adminCon = admin_connection();

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //make secretary button selected as default
        hoverInMouseClicked(btn_secretary);
        defaultAfterHover(btn_teacher);
        setIcon();

        // change cursor pointer to hand cursor in all buttons;
        changeCurssorWhenEnterButton(btn_login);
        changeCurssorWhenEnterButton(btn_secretary);
        changeCurssorWhenEnterButton(btn_teacher);
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(returnYourImageURL())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sp_login = new javax.swing.JScrollPane();
        pl_background = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        ol_login = new javax.swing.JPanel();
        pl_chooseUser = new javax.swing.JPanel();
        btn_teacher = new javax.swing.JButton();
        btn_secretary = new javax.swing.JButton();
        pl_loginData = new javax.swing.JPanel();
        tf_code = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        show = new javax.swing.JRadioButton();
        hide = new javax.swing.JRadioButton();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pl_background.setBackground(new java.awt.Color(255, 255, 255));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/login logo.jpg"))); // NOI18N

        ol_login.setBackground(new java.awt.Color(19, 64, 93));
        ol_login.setPreferredSize(new java.awt.Dimension(702, 600));

        pl_chooseUser.setBackground(new java.awt.Color(19, 64, 93));
        pl_chooseUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pl_chooseUser.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btn_teacher.setBackground(new java.awt.Color(19, 64, 93));
        btn_teacher.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        btn_teacher.setForeground(new java.awt.Color(255, 255, 255));
        btn_teacher.setText("معلم");
        btn_teacher.setContentAreaFilled(false);
        btn_teacher.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_teacher.setIconTextGap(16);
        btn_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_teacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_teacherMouseExited(evt);
            }
        });
        btn_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teacherActionPerformed(evt);
            }
        });
        pl_chooseUser.add(btn_teacher);

        btn_secretary.setBackground(new java.awt.Color(19, 64, 93));
        btn_secretary.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        btn_secretary.setForeground(new java.awt.Color(255, 255, 255));
        btn_secretary.setText("سكرتير");
        btn_secretary.setContentAreaFilled(false);
        btn_secretary.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_secretary.setIconTextGap(16);
        btn_secretary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_secretaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_secretaryMouseExited(evt);
            }
        });
        btn_secretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secretaryActionPerformed(evt);
            }
        });
        pl_chooseUser.add(btn_secretary);

        pl_loginData.setBackground(new java.awt.Color(19, 64, 93));
        pl_loginData.setLayout(new java.awt.GridLayout(2, 0, 0, 20));

        tf_code.setBackground(new java.awt.Color(19, 64, 93));
        tf_code.setFont(new java.awt.Font("Cairo", 0, 18)); // NOI18N
        tf_code.setForeground(new java.awt.Color(184, 198, 206));
        tf_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_code.setText("كود المستخدم");
        tf_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        tf_code.setCaretColor(new java.awt.Color(184, 198, 206));
        tf_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codeFocusLost(evt);
            }
        });
        tf_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codeKeyTyped(evt);
            }
        });
        pl_loginData.add(tf_code);

        pf_password.setBackground(new java.awt.Color(19, 64, 93));
        pf_password.setFont(new java.awt.Font("Cairo", 0, 18)); // NOI18N
        pf_password.setForeground(new java.awt.Color(184, 198, 206));
        pf_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pf_password.setText("كلمة المرور");
        pf_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pf_password.setCaretColor(new java.awt.Color(184, 198, 206));
        pf_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pf_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pf_passwordFocusLost(evt);
            }
        });
        pf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_passwordKeyPressed(evt);
            }
        });
        pl_loginData.add(pf_password);

        show.setBackground(new java.awt.Color(19, 64, 93));
        buttonGroup1.add(show);
        show.setFont(new java.awt.Font("Cairo", 0, 11)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("اظهار");
        show.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        hide.setBackground(new java.awt.Color(19, 64, 93));
        buttonGroup1.add(hide);
        hide.setFont(new java.awt.Font("Cairo", 0, 11)); // NOI18N
        hide.setForeground(new java.awt.Color(255, 255, 255));
        hide.setText("اخفاء");
        hide.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 155, 255));
        btn_login.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("تسجيل دخول");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ol_loginLayout = new javax.swing.GroupLayout(ol_login);
        ol_login.setLayout(ol_loginLayout);
        ol_loginLayout.setHorizontalGroup(
            ol_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ol_loginLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(pl_chooseUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ol_loginLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(hide)
                .addGap(10, 10, 10)
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ol_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(pl_loginData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(262, 262, 262))
        );
        ol_loginLayout.setVerticalGroup(
            ol_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ol_loginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(pl_chooseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ol_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ol_loginLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(pl_loginData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ol_loginLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(ol_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(show)
                            .addComponent(hide))))
                .addGap(101, 101, 101)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pl_backgroundLayout = new javax.swing.GroupLayout(pl_background);
        pl_background.setLayout(pl_backgroundLayout);
        pl_backgroundLayout.setHorizontalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_backgroundLayout.createSequentialGroup()
                .addComponent(lb_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ol_login, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
        );
        pl_backgroundLayout.setVerticalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ol_login, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        sp_login.setViewportView(pl_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_login, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_teacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_teacherMouseEntered


    }//GEN-LAST:event_btn_teacherMouseEntered

    private void btn_teacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_teacherMouseExited

    }//GEN-LAST:event_btn_teacherMouseExited

    private void btn_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teacherActionPerformed

        // view only month Cost panel
        // hover only Month Cost button
        hoverInMouseClicked(btn_teacher);
        defaultAfterHover(btn_secretary);

    }//GEN-LAST:event_btn_teacherActionPerformed

    private void btn_secretaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_secretaryMouseEntered

    }//GEN-LAST:event_btn_secretaryMouseEntered

    private void btn_secretaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_secretaryMouseExited


    }//GEN-LAST:event_btn_secretaryMouseExited

    private void btn_secretaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secretaryActionPerformed

        // hover only Month Cost button
        hoverInMouseClicked(btn_secretary);
        defaultAfterHover(btn_teacher);
    }//GEN-LAST:event_btn_secretaryActionPerformed

    private void tf_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusGained
        if (tf_code.getText().equals("كود المستخدم")) {
            tf_code.setText("");
        }
    }//GEN-LAST:event_tf_codeFocusGained

    private void tf_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusLost
        if (tf_code.getText().equals("")) {
            tf_code.setText("كود المستخدم");
        }
    }//GEN-LAST:event_tf_codeFocusLost

    private void tf_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeKeyPressed
        if (enter(evt.getKeyChar())) {
            pf_password.requestFocus(true);
        }
    }//GEN-LAST:event_tf_codeKeyPressed

    private void tf_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeKeyTyped

    }//GEN-LAST:event_tf_codeKeyTyped

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        pf_password.setEchoChar((char) 0);
    }//GEN-LAST:event_showActionPerformed

    private void hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideActionPerformed
        pf_password.setEchoChar('*');
    }//GEN-LAST:event_hideActionPerformed

    private void pf_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_passwordFocusGained
        if (pf_password.getText().equals("كلمة المرور")) {
            pf_password.setText("");
        }
    }//GEN-LAST:event_pf_passwordFocusGained

    private void pf_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_passwordFocusLost
        if (pf_password.getText().equals("")) {
            pf_password.setText("كلمة المرور");
        }
    }//GEN-LAST:event_pf_passwordFocusLost

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        String currentCode = tf_code.getText();
        String database_code = tf_code.getText();
        String password = pf_password.getText();
        String databasePassword = "";
        String name = "";
        PreparedStatement stmt;
        ResultSet res;
        SecretaryControl secretaryControl = new SecretaryControl();
        TeacherControl teacherControl = new TeacherControl();

        if (currentCode.equals("كود المستخدم") || password.equals("كلمة المرور")) {
            jOptionPaneMessage("تاكد من ملئ جميع البيانات بطريقة صحيحه", 0);
            return;
        }
        if (btn_teacher.isContentAreaFilled()) {
            try {
                stmt = adminCon.prepareStatement("select * from admin where admin_code=?");
                stmt.setString(1, currentCode);
                res = stmt.executeQuery();
                while (res.next()) {
                    database_code = res.getString("admin_code");
                    name = res.getString("admin_name");
                    databasePassword = res.getString("admin_password");
                }

                if (!database_code.equals("") && databasePassword.equals(password)) {
                    updateHolder(currentCode, name, password);
                    this.setVisible(false);
                    teacherControl.setVisible(true);

                    jOptionPaneMessage("تم تسجيل الدخول بنجاح " + "\n" + " اهلا بك يا  " + name, 1);
                } else {
                    jOptionPaneMessage("تاكد من الكود و كلمة المرور", 0);
                }
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }
        } else if (btn_secretary.isContentAreaFilled()) {
            try {
                stmt = con.prepareStatement("select * from secretary where secretary_code=?");
                stmt.setString(1, currentCode);
                res = stmt.executeQuery();
                while (res.next()) {
                    name = res.getString("secretary_name");
                    databasePassword = res.getString("secretary_password");
                }

                if (databasePassword.equals(password)) {
                    updateHolder(currentCode, name, password);
                    this.setVisible(false);
                    secretaryControl.setVisible(true);
                    jOptionPaneMessage("تم تسجيل الدخول بنجاح " + "\n" + " اهلا بك يا  " + name, 1);
                    recordEvent("تسجيل دخول", "تسجيل الدخول كسكرتير", "قام السكرتير بتسجيل الدخول");

                } else {
                    jOptionPaneMessage("تاكد من الكود و كلمة المرور", 0);
                }
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void pf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_passwordKeyPressed
        if (enter(evt.getKeyChar())) {

            String currentCode = tf_code.getText();
            String database_code = tf_code.getText();
            String password = pf_password.getText();
            String databasePassword = "";
            String name = "";
            PreparedStatement stmt;
            ResultSet res;
            SecretaryControl secretaryControl = new SecretaryControl();
            TeacherControl teacherControl = new TeacherControl();

            if (currentCode.equals("كود المستخدم") || password.equals("كلمة المرور")) {
                jOptionPaneMessage("تاكد من ملئ جميع البيانات بطريقة صحيحه", 0);
                return;
            }
            if (btn_teacher.isContentAreaFilled()) {
                try {
                    stmt = adminCon.prepareStatement("select * from admin where admin_code=?");
                    stmt.setString(1, currentCode);
                    res = stmt.executeQuery();
                    while (res.next()) {
                        database_code = res.getString("admin_code");
                        name = res.getString("admin_name");
                        databasePassword = res.getString("admin_password");
                    }

                    if (!database_code.equals("") && databasePassword.equals(password)) {
                        updateHolder(currentCode, name, password);
                        this.setVisible(false);
                        teacherControl.setVisible(true);

                        jOptionPaneMessage("تم تسجيل الدخول بنجاح " + "\n" + " اهلا بك يا  " + name, 1);
                    } else {
                        jOptionPaneMessage("تاكد من الكود و كلمة المرور", 0);
                    }
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            } else if (btn_secretary.isContentAreaFilled()) {
                try {
                    stmt = con.prepareStatement("select * from secretary where secretary_code=?");
                    stmt.setString(1, currentCode);
                    res = stmt.executeQuery();
                    while (res.next()) {
                        name = res.getString("secretary_name");
                        databasePassword = res.getString("secretary_password");
                    }

                    if (databasePassword.equals(password)) {
                        updateHolder(currentCode, name, password);
                        this.setVisible(false);
                        secretaryControl.setVisible(true);
                        jOptionPaneMessage("تم تسجيل الدخول بنجاح " + "\n" + " اهلا بك يا  " + name, 1);
                        recordEvent("تسجيل دخول", "تسجيل الدخول كسكرتير", "قام السكرتير بتسجيل الدخول");

                    } else {
                        jOptionPaneMessage("تاكد من الكود و كلمة المرور", 0);
                    }
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            }
        }
    }//GEN-LAST:event_pf_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_secretary;
    private javax.swing.JButton btn_teacher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton hide;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JPanel ol_login;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPanel pl_background;
    private javax.swing.JPanel pl_chooseUser;
    private javax.swing.JPanel pl_loginData;
    private javax.swing.JRadioButton show;
    private javax.swing.JScrollPane sp_login;
    private javax.swing.JTextField tf_code;
    // End of variables declaration//GEN-END:variables
}
