/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secretary;

import Login.Login;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static newatomicstudent.functions.*;

/**
 *
 * @author mahmo
 */
public class SecretaryProfile extends javax.swing.JFrame {

    Connection con = general_connection();

    /**
     * Creates new form Login
     */
    public SecretaryProfile() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();

        // show the profile panel
        pl_profile.setVisible(true);
        hoverInMouseClicked(btn_profile);
        tf_code.setText(loadHolderCode());
        tf_secretaryName.setText(loadHolderName());
        vrai.setVisible(false);
        vrai1.setVisible(false);
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(returnYourImageURL())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sp_login = new javax.swing.JScrollPane();
        pl_background = new javax.swing.JPanel();
        pl_login = new javax.swing.JPanel();
        lp_empty1 = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();
        pl_control = new javax.swing.JPanel();
        btn_setting = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        teacherProfile = new javax.swing.JLayeredPane();
        pl_profile = new javax.swing.JPanel();
        pl_teacherData = new javax.swing.JPanel();
        tf_code = new javax.swing.JTextField();
        lb_code = new javax.swing.JLabel();
        tf_secretaryName = new javax.swing.JTextField();
        lb_secretaryName = new javax.swing.JLabel();
        pl_passwordData = new javax.swing.JPanel();
        tf_oldSecretaryPassword = new javax.swing.JTextField();
        lb_teacherPassword1 = new javax.swing.JLabel();
        tf_newSecretaryPassword = new javax.swing.JTextField();
        lb_teacherPassword2 = new javax.swing.JLabel();
        tf_confirmSecretaryPassword = new javax.swing.JTextField();
        lb_teacherPassword3 = new javax.swing.JLabel();
        btn_updatePassword = new javax.swing.JButton();
        pl_horizontalBottomLine1 = new javax.swing.JPanel();
        vrai = new javax.swing.JLabel();
        vrai1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sp_login.setBackground(new java.awt.Color(255, 255, 255));

        pl_background.setBackground(new java.awt.Color(255, 255, 255));

        pl_login.setBackground(new java.awt.Color(19, 64, 93));
        pl_login.setPreferredSize(new java.awt.Dimension(702, 600));
        pl_login.setLayout(new java.awt.GridLayout(10, 0, 0, 15));
        pl_login.add(lp_empty1);

        btn_profile.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setText("بيانات تسجيل الدخول");
        btn_profile.setContentAreaFilled(false);
        btn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_profileMouseExited(evt);
            }
        });
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });
        pl_login.add(btn_profile);

        pl_control.setBackground(new java.awt.Color(19, 64, 93));
        pl_control.setPreferredSize(new java.awt.Dimension(702, 600));
        pl_control.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btn_setting.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile setting.png"))); // NOI18N
        btn_setting.setContentAreaFilled(false);
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_settingMouseExited(evt);
            }
        });
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });
        pl_control.add(btn_setting);

        btn_home.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile home.png"))); // NOI18N
        btn_home.setContentAreaFilled(false);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pl_control.add(btn_home);

        btn_logout.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile logout.png"))); // NOI18N
        btn_logout.setContentAreaFilled(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pl_control.add(btn_logout);

        teacherProfile.setLayout(new java.awt.CardLayout());

        pl_profile.setBackground(new java.awt.Color(255, 255, 255));

        pl_teacherData.setBackground(new java.awt.Color(255, 255, 255));
        pl_teacherData.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        tf_code.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_code.setToolTipText("اكتب كود الطالب و تاكد من ان يكون رقم صحيح");
        tf_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_code.setDisabledTextColor(new java.awt.Color(0, 153, 204));
        tf_code.setDoubleBuffered(true);
        tf_code.setEnabled(false);
        tf_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codeFocusLost(evt);
            }
        });
        tf_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeKeyPressed(evt);
            }
        });
        pl_teacherData.add(tf_code);

        lb_code.setBackground(new java.awt.Color(255, 255, 255));
        lb_code.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_code.setText("كود السكرتير");
        pl_teacherData.add(lb_code);

        tf_secretaryName.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_secretaryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_secretaryName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_secretaryName.setDisabledTextColor(new java.awt.Color(0, 153, 204));
        tf_secretaryName.setEnabled(false);
        tf_secretaryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_secretaryNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_secretaryNameFocusLost(evt);
            }
        });
        tf_secretaryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_secretaryNameKeyPressed(evt);
            }
        });
        pl_teacherData.add(tf_secretaryName);

        lb_secretaryName.setBackground(new java.awt.Color(255, 255, 255));
        lb_secretaryName.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_secretaryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_secretaryName.setText("اسم السكرتير");
        pl_teacherData.add(lb_secretaryName);

        pl_passwordData.setBackground(new java.awt.Color(255, 255, 255));
        pl_passwordData.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        tf_oldSecretaryPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_oldSecretaryPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_oldSecretaryPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_oldSecretaryPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_oldSecretaryPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_oldSecretaryPasswordFocusLost(evt);
            }
        });
        tf_oldSecretaryPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_oldSecretaryPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_oldSecretaryPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_oldSecretaryPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_oldSecretaryPassword);

        lb_teacherPassword1.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword1.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword1.setText("كلمة المرور الحالية");
        pl_passwordData.add(lb_teacherPassword1);

        tf_newSecretaryPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_newSecretaryPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_newSecretaryPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_newSecretaryPassword.setDragEnabled(true);
        tf_newSecretaryPassword.setEnabled(false);
        tf_newSecretaryPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_newSecretaryPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_newSecretaryPasswordFocusLost(evt);
            }
        });
        tf_newSecretaryPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_newSecretaryPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_newSecretaryPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_newSecretaryPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_newSecretaryPassword);

        lb_teacherPassword2.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword2.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword2.setText("كلمة المرور الجديدة");
        pl_passwordData.add(lb_teacherPassword2);

        tf_confirmSecretaryPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_confirmSecretaryPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_confirmSecretaryPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_confirmSecretaryPassword.setEnabled(false);
        tf_confirmSecretaryPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_confirmSecretaryPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_confirmSecretaryPasswordFocusLost(evt);
            }
        });
        tf_confirmSecretaryPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_confirmSecretaryPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_confirmSecretaryPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_confirmSecretaryPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_confirmSecretaryPassword);

        lb_teacherPassword3.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword3.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword3.setText("تاكيد كلمة المرور الجديدة");
        pl_passwordData.add(lb_teacherPassword3);

        btn_updatePassword.setBackground(new java.awt.Color(0, 155, 255));
        btn_updatePassword.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_updatePassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_updatePassword.setText("تغيير كلمة المرور");
        btn_updatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatePasswordActionPerformed(evt);
            }
        });

        pl_horizontalBottomLine1.setBackground(new java.awt.Color(102, 102, 102));
        pl_horizontalBottomLine1.setMinimumSize(new java.awt.Dimension(440, 5));
        pl_horizontalBottomLine1.setPreferredSize(new java.awt.Dimension(800, 2));

        javax.swing.GroupLayout pl_horizontalBottomLine1Layout = new javax.swing.GroupLayout(pl_horizontalBottomLine1);
        pl_horizontalBottomLine1.setLayout(pl_horizontalBottomLine1Layout);
        pl_horizontalBottomLine1Layout.setHorizontalGroup(
            pl_horizontalBottomLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pl_horizontalBottomLine1Layout.setVerticalGroup(
            pl_horizontalBottomLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        vrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/vrai.png"))); // NOI18N

        vrai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/vrai.png"))); // NOI18N

        javax.swing.GroupLayout pl_profileLayout = new javax.swing.GroupLayout(pl_profile);
        pl_profile.setLayout(pl_profileLayout);
        pl_profileLayout.setHorizontalGroup(
            pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_profileLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pl_teacherData, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pl_profileLayout.createSequentialGroup()
                                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vrai)
                                    .addGroup(pl_profileLayout.createSequentialGroup()
                                        .addComponent(vrai1)
                                        .addGap(0, 0, 0)))
                                .addComponent(pl_passwordData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addComponent(pl_horizontalBottomLine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addComponent(btn_updatePassword)
                        .addGap(194, 194, 194))))
        );
        pl_profileLayout.setVerticalGroup(
            pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_profileLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pl_teacherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pl_horizontalBottomLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pl_passwordData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pl_profileLayout.createSequentialGroup()
                        .addComponent(vrai1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vrai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_updatePassword)
                .addGap(204, 204, 204))
        );

        teacherProfile.add(pl_profile, "card2");

        javax.swing.GroupLayout pl_backgroundLayout = new javax.swing.GroupLayout(pl_background);
        pl_background.setLayout(pl_backgroundLayout);
        pl_backgroundLayout.setHorizontalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_backgroundLayout.createSequentialGroup()
                .addGroup(pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_backgroundLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(pl_control, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(316, 316, 316))
                    .addComponent(teacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pl_login, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pl_backgroundLayout.setVerticalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_backgroundLayout.createSequentialGroup()
                .addGroup(pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_backgroundLayout.createSequentialGroup()
                        .addComponent(pl_control, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherProfile))
                    .addComponent(pl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        sp_login.setViewportView(pl_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sp_login, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseEntered
        if (pl_profile.isVisible() != true) {
            hoverInMouseMotion(btn_profile);
        }
    }//GEN-LAST:event_btn_profileMouseEntered

    private void btn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseExited
        if (pl_profile.isVisible() != true) {
            defaultAfterHover(btn_profile);
        }
    }//GEN-LAST:event_btn_profileMouseExited

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        pl_profile.setVisible(true);
        hoverInMouseClicked(btn_profile);
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseEntered
        hoverInMouseMotion(btn_setting);
    }//GEN-LAST:event_btn_settingMouseEntered

    private void btn_settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseExited
        defaultAfterHover(btn_setting);
    }//GEN-LAST:event_btn_settingMouseExited

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        this.setVisible(false);
        Settings Settings = new Settings();
        if (this.getExtendedState() != 0) {
            Settings.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        Settings.setVisible(true);
    }//GEN-LAST:event_btn_settingActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        this.setVisible(false);
        SecretaryControl secretaryControl = new SecretaryControl();
        if (this.getExtendedState() != 0) {
            secretaryControl.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        secretaryControl.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        hoverInMouseMotion(btn_logout);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        defaultAfterHover(btn_logout);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تسجيل الخروج", "استفهام", JOptionPane.YES_NO_OPTION, 1);
        if (yes == JOptionPane.YES_OPTION) {
            Login l = new Login();
            this.setVisible(false);
            l.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        hoverInMouseMotion(btn_home);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        defaultAfterHover(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_updatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatePasswordActionPerformed
        // check that the important field isn't empty
        if (checkEmpty(tf_oldSecretaryPassword) && checkEmpty(tf_newSecretaryPassword) && checkEmpty(tf_confirmSecretaryPassword)) {
            String secretary_code = loadHolderCode();
            String secretary_name = loadHolderName();
            String currentPassword = tf_oldSecretaryPassword.getText();
            String newPassword = tf_newSecretaryPassword.getText();
            String confrimationPassword = tf_confirmSecretaryPassword.getText();
            PreparedStatement stmt;
            if (currentPassword.equals(loadHolderPassword())) {
                if (newPassword.equals(confrimationPassword)) {
                    int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تغيير كلمة المرور ", "استفهام", JOptionPane.YES_NO_OPTION, 1);
                    if (yes == JOptionPane.YES_OPTION) {
                        try {
                            stmt = con.prepareStatement("update secretary set  secretary_password=? where secretary_code=?");
                            stmt.setString(1, newPassword);
                            stmt.setString(2, secretary_code);
                            stmt.execute();
                            updateMessage();
                            updateHolder(secretary_code, secretary_name, newPassword);
                            recordEvent("كلمة المرور", "تغيير كلمة المرور", "قام السكرتير " + secretary_name + "بتغيير كلمة المرور الى" + confrimationPassword);
                            cleanAfterUpdatePassword();
                        } catch (SQLException ex) {
                            handleSqlExceptions(ex.getErrorCode());
                        }
                    }
                } else {
                    makeRed(tf_confirmSecretaryPassword);
                    jOptionPaneMessage("كلمة المرور الجديده غير مطابقة", 0);
                }
            } else {
                makeRed(tf_oldSecretaryPassword);
                jOptionPaneMessage("غير مطابق لكلمة المرور الحالية", 0);
            }
        }
    }//GEN-LAST:event_btn_updatePasswordActionPerformed

    private void tf_confirmSecretaryPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmSecretaryPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            // check that the important field isn't empty
            if (checkEmpty(tf_oldSecretaryPassword) && checkEmpty(tf_newSecretaryPassword) && checkEmpty(tf_confirmSecretaryPassword)) {
                String secretary_code = loadHolderCode();
                String secretary_name = loadHolderName();
                String currentPassword = tf_oldSecretaryPassword.getText();
                String newPassword = tf_newSecretaryPassword.getText();
                String confrimationPassword = tf_confirmSecretaryPassword.getText();
                PreparedStatement stmt;
                if (currentPassword.equals(loadHolderPassword())) {
                    if (newPassword.equals(confrimationPassword)) {
                        int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تغيير كلمة المرور ", "استفهام", JOptionPane.YES_NO_OPTION, 1);
                        if (yes == JOptionPane.YES_OPTION) {
                            try {
                                stmt = con.prepareStatement("update secretary set  secretary_password=? where secretary_code=?");
                                stmt.setString(1, newPassword);
                                stmt.setString(2, secretary_code);
                                stmt.execute();
                                updateMessage();
                                updateHolder(secretary_code, secretary_name, newPassword);
                                cleanAfterUpdatePassword();
                            } catch (SQLException ex) {
                                handleSqlExceptions(ex.getErrorCode());
                            }
                        }
                    } else {
                        makeRed(tf_confirmSecretaryPassword);
                        jOptionPaneMessage("كلمة المرور الجديده غير مطابقة", 0);
                    }
                } else {
                    makeRed(tf_oldSecretaryPassword);
                    jOptionPaneMessage("غير مطابق لكلمة المرور الحالية", 0);
                }
            }
        }
    }//GEN-LAST:event_tf_confirmSecretaryPasswordKeyPressed

    private void tf_confirmSecretaryPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_confirmSecretaryPasswordFocusLost
        FocusLostOrGained(tf_confirmSecretaryPassword);
    }//GEN-LAST:event_tf_confirmSecretaryPasswordFocusLost

    private void tf_confirmSecretaryPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_confirmSecretaryPasswordFocusGained
        FocusLostOrGained(tf_confirmSecretaryPassword);
    }//GEN-LAST:event_tf_confirmSecretaryPasswordFocusGained

    private void tf_newSecretaryPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newSecretaryPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_confirmSecretaryPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_newSecretaryPasswordKeyPressed

    private void tf_newSecretaryPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_newSecretaryPasswordFocusLost
        FocusLostOrGained(tf_newSecretaryPassword);
    }//GEN-LAST:event_tf_newSecretaryPasswordFocusLost

    private void tf_newSecretaryPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_newSecretaryPasswordFocusGained
        FocusLostOrGained(tf_newSecretaryPassword);
    }//GEN-LAST:event_tf_newSecretaryPasswordFocusGained

    private void tf_oldSecretaryPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldSecretaryPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_newSecretaryPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_oldSecretaryPasswordKeyPressed

    private void tf_oldSecretaryPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_oldSecretaryPasswordFocusLost
        FocusLostOrGained(tf_oldSecretaryPassword);
    }//GEN-LAST:event_tf_oldSecretaryPasswordFocusLost

    private void tf_oldSecretaryPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_oldSecretaryPasswordFocusGained
        FocusLostOrGained(tf_oldSecretaryPassword);
    }//GEN-LAST:event_tf_oldSecretaryPasswordFocusGained

    private void tf_secretaryNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_secretaryNameKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_oldSecretaryPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_secretaryNameKeyPressed

    private void tf_secretaryNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryNameFocusLost
        FocusLostOrGained(tf_secretaryName);
    }//GEN-LAST:event_tf_secretaryNameFocusLost

    private void tf_secretaryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryNameFocusGained
        FocusLostOrGained(tf_secretaryName);
    }//GEN-LAST:event_tf_secretaryNameFocusGained

    private void tf_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_secretaryName.requestFocus(true);
        }
    }//GEN-LAST:event_tf_codeKeyPressed

    private void tf_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusLost
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusLost

    private void tf_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusGained
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusGained

    private void tf_confirmSecretaryPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmSecretaryPasswordKeyTyped
        if (tf_confirmSecretaryPassword.getText().equals(tf_newSecretaryPassword.getText())) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_confirmSecretaryPasswordKeyTyped

    private void tf_oldSecretaryPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldSecretaryPasswordKeyTyped
        if (tf_oldSecretaryPassword.getText().equals(loadHolderPassword())) {
            vrai1.setVisible(true);
            tf_newSecretaryPassword.setEnabled(true);
            tf_confirmSecretaryPassword.setEnabled(true);
            vrai.setVisible(true);
        } else {
            vrai1.setVisible(false);
            tf_newSecretaryPassword.setEnabled(false);
            tf_confirmSecretaryPassword.setEnabled(false);
            vrai1.setVisible(false);
        }
    }//GEN-LAST:event_tf_oldSecretaryPasswordKeyTyped

    private void tf_oldSecretaryPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldSecretaryPasswordKeyReleased
        if (tf_oldSecretaryPassword.getText().equals(loadHolderPassword())) {
            vrai1.setVisible(true);
            tf_newSecretaryPassword.setEnabled(true);
            tf_confirmSecretaryPassword.setEnabled(true);
        } else {
            vrai1.setVisible(false);
            tf_newSecretaryPassword.setEnabled(false);
            tf_confirmSecretaryPassword.setEnabled(false);
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_oldSecretaryPasswordKeyReleased

    private void tf_confirmSecretaryPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmSecretaryPasswordKeyReleased
        if (tf_confirmSecretaryPassword.getText().equals(tf_newSecretaryPassword.getText()) && !tf_newSecretaryPassword.getText().equals("") && !tf_confirmSecretaryPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_confirmSecretaryPasswordKeyReleased

    private void tf_newSecretaryPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newSecretaryPasswordKeyTyped
        if (tf_confirmSecretaryPassword.getText().equals(tf_newSecretaryPassword.getText()) && !tf_newSecretaryPassword.getText().equals("") && !tf_confirmSecretaryPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_newSecretaryPasswordKeyTyped

    private void tf_newSecretaryPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newSecretaryPasswordKeyReleased
        if (tf_confirmSecretaryPassword.getText().equals(tf_newSecretaryPassword.getText()) && !tf_newSecretaryPassword.getText().equals("") && !tf_confirmSecretaryPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_newSecretaryPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_updatePassword;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_secretaryName;
    private javax.swing.JLabel lb_teacherPassword1;
    private javax.swing.JLabel lb_teacherPassword2;
    private javax.swing.JLabel lb_teacherPassword3;
    private javax.swing.JLabel lp_empty1;
    private javax.swing.JPanel pl_background;
    private javax.swing.JPanel pl_control;
    private javax.swing.JPanel pl_horizontalBottomLine1;
    private javax.swing.JPanel pl_login;
    private javax.swing.JPanel pl_passwordData;
    private javax.swing.JPanel pl_profile;
    private javax.swing.JPanel pl_teacherData;
    private javax.swing.JScrollPane sp_login;
    private javax.swing.JLayeredPane teacherProfile;
    private javax.swing.JTextField tf_code;
    private javax.swing.JTextField tf_confirmSecretaryPassword;
    private javax.swing.JTextField tf_newSecretaryPassword;
    private javax.swing.JTextField tf_oldSecretaryPassword;
    private javax.swing.JTextField tf_secretaryName;
    private javax.swing.JLabel vrai;
    private javax.swing.JLabel vrai1;
    // End of variables declaration//GEN-END:variables

    private void cleanAfterUpdatePassword() {
        tf_oldSecretaryPassword.setText("");
        tf_newSecretaryPassword.setText("");
        tf_confirmSecretaryPassword.setText("");
        FocusLostOrGained(tf_oldSecretaryPassword);
        FocusLostOrGained(tf_newSecretaryPassword);
        FocusLostOrGained(tf_confirmSecretaryPassword);
        vrai.setVisible(false);
        vrai1.setVisible(false);
    }
}
