/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import static newatomicstudent.functions.*;

/**
 *
 * @author mahmo
 */
public class SecretaryManagement extends javax.swing.JFrame {

    // general_connection with the database
    Connection con;
    DefaultListModel dlm14 = new DefaultListModel();

    /**
     * Creates new form StudentManagement
     */
    public SecretaryManagement() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();
        // connect to the database
        con = general_connection();

        // set all panels not visible except add panel and make the button add student request focus
        hoverInMouseClicked(btn_add);
        pl_addingStudent.setVisible(true);

        //************************ this for adding panel********************///////
        // load the data of the secretary in the table viewSecretaryData
        loadSecretary(t_viewSecretaryData);
        // change cursor pointer to hand cursor in all buttons;
        changeCurssorWhenEnterButton(btn_Setting);
        changeCurssorWhenEnterButton(btn_add);
        changeCurssorWhenEnterButton(btn_clean1);
        changeCurssorWhenEnterButton(btn_delete2);
        changeCurssorWhenEnterButton(btn_home);
        changeCurssorWhenEnterButton(btn_save);
        changeCurssorWhenEnterButton(btn_update1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        sp_secretaryManagement = new javax.swing.JScrollPane();
        pl_background = new javax.swing.JPanel();
        pl_topButtonControl = new javax.swing.JPanel();
        lp_empty = new javax.swing.JLabel();
        lp_empty1 = new javax.swing.JLabel();
        lp_empty2 = new javax.swing.JLabel();
        lp_empty4 = new javax.swing.JLabel();
        lp_empty3 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        secretaryManagement = new javax.swing.JLayeredPane();
        pl_addingStudent = new javax.swing.JPanel();
        pl_horizontalTopLine = new javax.swing.JPanel();
        pl_verticalLine = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        lb_star4 = new javax.swing.JLabel();
        lb_star5 = new javax.swing.JLabel();
        pl_secretaryData = new javax.swing.JPanel();
        tf_code = new javax.swing.JTextField();
        lb_code = new javax.swing.JLabel();
        tf_secretaryName = new javax.swing.JTextField();
        lb_secretaryName = new javax.swing.JLabel();
        tf_secretaryPassword = new javax.swing.JTextField();
        lb_secretaryPassword = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        lb_star15 = new javax.swing.JLabel();
        btn_clean1 = new javax.swing.JButton();
        sp_secretaryData = new javax.swing.JScrollPane();
        t_viewSecretaryData = new javax.swing.JTable();
        btn_delete2 = new javax.swing.JButton();
        btn_update1 = new javax.swing.JButton();
        pl_bottomButtonCotrol = new javax.swing.JPanel();
        lb_empty3 = new javax.swing.JLabel();
        lb_empty4 = new javax.swing.JLabel();
        lb_empty5 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_Setting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pl_background.setBackground(new java.awt.Color(255, 255, 255));
        pl_background.setMinimumSize(new java.awt.Dimension(1205, 650));

        pl_topButtonControl.setBackground(new java.awt.Color(19, 64, 93));
        pl_topButtonControl.setMinimumSize(new java.awt.Dimension(1205, 60));
        pl_topButtonControl.setPreferredSize(new java.awt.Dimension(1205, 60));
        pl_topButtonControl.setLayout(new java.awt.GridLayout(1, 0, 10, 10));
        pl_topButtonControl.add(lp_empty);
        pl_topButtonControl.add(lp_empty1);
        pl_topButtonControl.add(lp_empty2);
        pl_topButtonControl.add(lp_empty4);
        pl_topButtonControl.add(lp_empty3);

        btn_add.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("ادارة السكرتارية");
        btn_add.setContentAreaFilled(false);
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pl_topButtonControl.add(btn_add);

        secretaryManagement.setPreferredSize(new java.awt.Dimension(1205, 553));
        secretaryManagement.setLayout(new java.awt.CardLayout());

        pl_addingStudent.setBackground(new java.awt.Color(255, 255, 255));
        pl_addingStudent.setPreferredSize(new java.awt.Dimension(1205, 541));

        pl_horizontalTopLine.setBackground(new java.awt.Color(0, 155, 255));
        pl_horizontalTopLine.setMinimumSize(new java.awt.Dimension(440, 5));

        javax.swing.GroupLayout pl_horizontalTopLineLayout = new javax.swing.GroupLayout(pl_horizontalTopLine);
        pl_horizontalTopLine.setLayout(pl_horizontalTopLineLayout);
        pl_horizontalTopLineLayout.setHorizontalGroup(
            pl_horizontalTopLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pl_horizontalTopLineLayout.setVerticalGroup(
            pl_horizontalTopLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pl_verticalLine.setBackground(new java.awt.Color(0, 155, 255));

        javax.swing.GroupLayout pl_verticalLineLayout = new javax.swing.GroupLayout(pl_verticalLine);
        pl_verticalLine.setLayout(pl_verticalLineLayout);
        pl_verticalLineLayout.setHorizontalGroup(
            pl_verticalLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pl_verticalLineLayout.setVerticalGroup(
            pl_verticalLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        lb_title.setBackground(new java.awt.Color(255, 255, 255));
        lb_title.setFont(new java.awt.Font("Cairo", 1, 30)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("ادارة السكرتارية:-");

        lb_star4.setBackground(new java.awt.Color(255, 255, 255));
        lb_star4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_star4.setForeground(new java.awt.Color(255, 0, 0));
        lb_star4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_star4.setText("*");
        lb_star4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lb_star5.setBackground(new java.awt.Color(255, 255, 255));
        lb_star5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_star5.setForeground(new java.awt.Color(255, 0, 0));
        lb_star5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_star5.setText("*");
        lb_star5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        pl_secretaryData.setBackground(new java.awt.Color(255, 255, 255));
        pl_secretaryData.setLayout(new java.awt.GridLayout(3, 2, 30, 30));

        tf_code.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_code.setToolTipText("");
        tf_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_code.setDoubleBuffered(true);
        tf_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codeFocusLost(evt);
            }
        });
        tf_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeKeyPressed(evt);
            }
        });
        pl_secretaryData.add(tf_code);
        tf_code.getAccessibleContext().setAccessibleName("");

        lb_code.setBackground(new java.awt.Color(255, 255, 255));
        lb_code.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        lb_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_code.setText("كود السكرتير");
        pl_secretaryData.add(lb_code);

        tf_secretaryName.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_secretaryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_secretaryName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_secretaryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_secretaryNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_secretaryNameFocusLost(evt);
            }
        });
        tf_secretaryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_secretaryNameKeyPressed(evt);
            }
        });
        pl_secretaryData.add(tf_secretaryName);

        lb_secretaryName.setBackground(new java.awt.Color(255, 255, 255));
        lb_secretaryName.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        lb_secretaryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_secretaryName.setText("اسم السكرتير");
        pl_secretaryData.add(lb_secretaryName);

        tf_secretaryPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_secretaryPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_secretaryPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_secretaryPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_secretaryPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_secretaryPasswordFocusLost(evt);
            }
        });
        tf_secretaryPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_secretaryPasswordKeyPressed(evt);
            }
        });
        pl_secretaryData.add(tf_secretaryPassword);

        lb_secretaryPassword.setBackground(new java.awt.Color(255, 255, 255));
        lb_secretaryPassword.setFont(new java.awt.Font("Cairo", 1, 24)); // NOI18N
        lb_secretaryPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_secretaryPassword.setText("الباسورد");
        pl_secretaryData.add(lb_secretaryPassword);

        btn_save.setBackground(new java.awt.Color(0, 155, 255));
        btn_save.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("اضافة");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        lb_star15.setBackground(new java.awt.Color(255, 255, 255));
        lb_star15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_star15.setForeground(new java.awt.Color(255, 0, 0));
        lb_star15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_star15.setText("*");
        lb_star15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btn_clean1.setBackground(new java.awt.Color(153, 153, 153));
        btn_clean1.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_clean1.setForeground(new java.awt.Color(255, 255, 255));
        btn_clean1.setText("تنظيف");
        btn_clean1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clean1ActionPerformed(evt);
            }
        });

        t_viewSecretaryData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        t_viewSecretaryData.setFont(new java.awt.Font("Cairo", 1, 11)); // NOI18N
        t_viewSecretaryData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الباسورد", "الاسم", "الكود"
            }
        ));
        t_viewSecretaryData.setRowHeight(30);
        t_viewSecretaryData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_viewSecretaryDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_viewSecretaryDataMouseEntered(evt);
            }
        });
        sp_secretaryData.setViewportView(t_viewSecretaryData);

        btn_delete2.setBackground(new java.awt.Color(153, 0, 0));
        btn_delete2.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_delete2.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete2.setText("حذف");
        btn_delete2.setEnabled(false);
        btn_delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete2ActionPerformed(evt);
            }
        });

        btn_update1.setBackground(new java.awt.Color(0, 0, 0));
        btn_update1.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_update1.setForeground(new java.awt.Color(255, 255, 255));
        btn_update1.setText("تعديل");
        btn_update1.setEnabled(false);
        btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pl_addingStudentLayout = new javax.swing.GroupLayout(pl_addingStudent);
        pl_addingStudent.setLayout(pl_addingStudentLayout);
        pl_addingStudentLayout.setHorizontalGroup(
            pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                .addGap(861, 954, Short.MAX_VALUE)
                .addComponent(lb_title)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                        .addComponent(btn_delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                        .addComponent(sp_secretaryData, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(pl_verticalLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                                .addComponent(pl_horizontalTopLine, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                                .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pl_addingStudentLayout.createSequentialGroup()
                                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_clean1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pl_addingStudentLayout.createSequentialGroup()
                                        .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lb_star5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_star4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_star15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pl_secretaryData, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51))))))
        );
        pl_addingStudentLayout.setVerticalGroup(
            pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_addingStudentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_secretaryData, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pl_verticalLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pl_addingStudentLayout.createSequentialGroup()
                        .addComponent(pl_horizontalTopLine, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pl_secretaryData, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pl_addingStudentLayout.createSequentialGroup()
                                .addComponent(lb_star4)
                                .addGap(42, 42, 42)
                                .addComponent(lb_star5)
                                .addGap(51, 51, 51)
                                .addComponent(lb_star15)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clean1)
                            .addComponent(btn_save))))
                .addGroup(pl_addingStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_addingStudentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_update1))
                    .addGroup(pl_addingStudentLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_delete2)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        secretaryManagement.add(pl_addingStudent, "card7");

        pl_bottomButtonCotrol.setBackground(new java.awt.Color(19, 64, 93));
        pl_bottomButtonCotrol.setMinimumSize(new java.awt.Dimension(1205, 60));
        pl_bottomButtonCotrol.setPreferredSize(new java.awt.Dimension(1205, 60));
        pl_bottomButtonCotrol.setLayout(new java.awt.GridLayout(1, 0, 30, 0));
        pl_bottomButtonCotrol.add(lb_empty3);
        pl_bottomButtonCotrol.add(lb_empty4);
        pl_bottomButtonCotrol.add(lb_empty5);

        btn_home.setBackground(new java.awt.Color(19, 64, 93));
        btn_home.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-btn.png"))); // NOI18N
        btn_home.setText("الرئيسية");
        btn_home.setContentAreaFilled(false);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_home.setIconTextGap(16);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pl_bottomButtonCotrol.add(btn_home);

        btn_Setting.setBackground(new java.awt.Color(19, 64, 93));
        btn_Setting.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_Setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Settings.png"))); // NOI18N
        btn_Setting.setText("الاعدادات");
        btn_Setting.setContentAreaFilled(false);
        btn_Setting.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_Setting.setIconTextGap(16);
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });
        btn_Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SettingActionPerformed(evt);
            }
        });
        pl_bottomButtonCotrol.add(btn_Setting);

        javax.swing.GroupLayout pl_backgroundLayout = new javax.swing.GroupLayout(pl_background);
        pl_background.setLayout(pl_backgroundLayout);
        pl_backgroundLayout.setHorizontalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_topButtonControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secretaryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pl_bottomButtonCotrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pl_backgroundLayout.setVerticalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_backgroundLayout.createSequentialGroup()
                .addComponent(pl_topButtonControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secretaryManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pl_bottomButtonCotrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sp_secretaryManagement.setViewportView(pl_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_secretaryManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_secretaryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(returnYourImageURL())));
    }

    public void cleanAfterAddOrUpdateOrDeleteSecretary() {
        tf_code.setText("");
        tf_secretaryName.setText("");
        tf_secretaryPassword.setText("");
        FocusLostOrGained(tf_code);
        FocusLostOrGained(tf_secretaryName);
        FocusLostOrGained(tf_secretaryPassword);
        btn_save.setEnabled(true);
        btn_delete2.setEnabled(false);
        btn_update1.setEnabled(false);
        tf_code.setEnabled(true);
    }

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        if (pl_addingStudent.isVisible() == false) {
            hoverInMouseMotion(btn_add);
        }
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        if (pl_addingStudent.isVisible() != true) {
            btn_add.setContentAreaFilled(false);
        }

    }//GEN-LAST:event_btn_addMouseExited

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String code;
        String name;
        String password;
        PreparedStatement stmt;
        //check whethear the data is empty;
        if (checkEmpty(tf_code) && checkEmpty(tf_secretaryName) && checkEmpty(tf_secretaryPassword)) {
            code = tf_code.getText();
            name = tf_secretaryName.getText();
            password = tf_secretaryPassword.getText();
            try {
                stmt = con.prepareStatement("insert into secretary values(?,?,?)");
                stmt.setString(1, code);
                stmt.setString(2, name);
                stmt.setString(3, password);
                stmt.execute();
                addMessage();
                cleanAfterAddOrUpdateOrDeleteSecretary();
                loadSecretary(t_viewSecretaryData);
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }

        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        // view only add panel  
        pl_addingStudent.setVisible(true);

        // hover only add button
        hoverInMouseClicked(btn_add);

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        hoverInMouseMotion(btn_Setting);
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        defaultAfterHover(btn_Setting);
    }//GEN-LAST:event_btn_SettingMouseExited

    private void btn_SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SettingActionPerformed
        this.setVisible(false);
        TeacherSettings teacherSettings = new TeacherSettings();
        if (this.getExtendedState() != 0) {
            teacherSettings.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherSettings.setVisible(true);
    }//GEN-LAST:event_btn_SettingActionPerformed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        hoverInMouseMotion(btn_home);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        defaultAfterHover(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        this.setVisible(false);
        TeacherControl teacherControl = new TeacherControl();
        if (this.getExtendedState() != 0) {
            teacherControl.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherControl.setVisible(true);

    }//GEN-LAST:event_btn_homeActionPerformed

    private void tf_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_secretaryName.requestFocus(true);

        }
    }//GEN-LAST:event_tf_codeKeyPressed

    private void tf_secretaryNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_secretaryNameKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_secretaryPassword.requestFocus(true);
        }

    }//GEN-LAST:event_tf_secretaryNameKeyPressed

    private void tf_secretaryPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_secretaryPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            String code;
            String name;
            String password;
            PreparedStatement stmt;
            //check whethear the data is empty;
            if (checkEmpty(tf_code) && checkEmpty(tf_secretaryName) && checkEmpty(tf_secretaryPassword)) {
                code = tf_code.getText();
                name = tf_secretaryName.getText();
                password = tf_secretaryPassword.getText();
                try {
                    stmt = con.prepareStatement("insert into secretary values(?,?,?)");
                    stmt.setString(1, code);
                    stmt.setString(2, name);
                    stmt.setString(3, password);
                    stmt.execute();
                    addMessage();
                    cleanAfterAddOrUpdateOrDeleteSecretary();
                    loadSecretary(t_viewSecretaryData);
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }

            }

        }
    }//GEN-LAST:event_tf_secretaryPasswordKeyPressed

    private void tf_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusLost
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusLost

    private void tf_secretaryPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryPasswordFocusLost
        FocusLostOrGained(tf_secretaryPassword);
    }//GEN-LAST:event_tf_secretaryPasswordFocusLost

    private void tf_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusGained
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusGained

    private void tf_secretaryPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryPasswordFocusGained
        FocusLostOrGained(tf_secretaryPassword);
    }//GEN-LAST:event_tf_secretaryPasswordFocusGained

    private void tf_secretaryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryNameFocusGained
        FocusLostOrGained(tf_secretaryName);
    }//GEN-LAST:event_tf_secretaryNameFocusGained

    private void tf_secretaryNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_secretaryNameFocusLost
        FocusLostOrGained(tf_secretaryName);
    }//GEN-LAST:event_tf_secretaryNameFocusLost

    private void btn_clean1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clean1ActionPerformed
        cleanAfterAddOrUpdateOrDeleteSecretary();
    }//GEN-LAST:event_btn_clean1ActionPerformed

    private void btn_delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete2ActionPerformed
        String code;
        PreparedStatement stmt;
        //check whethear the data is empty;
        if (checkEmpty(tf_code)) {
            code = tf_code.getText();
            try {
                stmt = con.prepareStatement("delete from secretary where secretary_code=?");
                stmt.setString(1, code);
                stmt.execute();
                deleteMessage();
                cleanAfterAddOrUpdateOrDeleteSecretary();
                loadSecretary(t_viewSecretaryData);
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_btn_delete2ActionPerformed

    private void btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update1ActionPerformed
        String code;
        String name;
        String password;
        PreparedStatement stmt;
        //check whethear the data is empty;
        if (checkEmpty(tf_code) && checkEmpty(tf_secretaryName) && checkEmpty(tf_secretaryPassword)) {
            code = tf_code.getText();
            name = tf_secretaryName.getText();
            password = tf_secretaryPassword.getText();
            try {
                stmt = con.prepareStatement("update secretary set secretary_name=?, secretary_password=? where secretary_code=?");
                stmt.setString(1, name);
                stmt.setString(2, password);
                stmt.setString(3, code);
                stmt.execute();
                updateMessage();
                cleanAfterAddOrUpdateOrDeleteSecretary();
                loadSecretary(t_viewSecretaryData);
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }
        }
    }//GEN-LAST:event_btn_update1ActionPerformed

    private void t_viewSecretaryDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_viewSecretaryDataMouseEntered

    }//GEN-LAST:event_t_viewSecretaryDataMouseEntered

    private void t_viewSecretaryDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_viewSecretaryDataMouseClicked
        FocusLostOrGained(tf_code);
        FocusLostOrGained(tf_secretaryName);
        FocusLostOrGained(tf_secretaryPassword);
        btn_update1.setEnabled(true);
        btn_delete2.setEnabled(true);
        tf_code.setEnabled(false);
        btn_save.setEnabled(false);
        TableModel model1 = t_viewSecretaryData.getModel();
        int[] index = t_viewSecretaryData.getSelectedRows();
        for (int i = 0; i < index.length; i++) {
            tf_secretaryPassword.setText(String.valueOf(model1.getValueAt(index[i], 0)));
            tf_secretaryName.setText(String.valueOf(model1.getValueAt(index[i], 1)));
            tf_code.setText(String.valueOf(model1.getValueAt(index[i], 2)));
        }
    }//GEN-LAST:event_t_viewSecretaryDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Setting;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clean1;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_empty3;
    private javax.swing.JLabel lb_empty4;
    private javax.swing.JLabel lb_empty5;
    private javax.swing.JLabel lb_secretaryName;
    private javax.swing.JLabel lb_secretaryPassword;
    private javax.swing.JLabel lb_star15;
    private javax.swing.JLabel lb_star4;
    private javax.swing.JLabel lb_star5;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lp_empty;
    private javax.swing.JLabel lp_empty1;
    private javax.swing.JLabel lp_empty2;
    private javax.swing.JLabel lp_empty3;
    private javax.swing.JLabel lp_empty4;
    private javax.swing.JPanel pl_addingStudent;
    private javax.swing.JPanel pl_background;
    private javax.swing.JPanel pl_bottomButtonCotrol;
    private javax.swing.JPanel pl_horizontalTopLine;
    private javax.swing.JPanel pl_secretaryData;
    private javax.swing.JPanel pl_topButtonControl;
    private javax.swing.JPanel pl_verticalLine;
    private javax.swing.JLayeredPane secretaryManagement;
    private javax.swing.JScrollPane sp_secretaryData;
    private javax.swing.JScrollPane sp_secretaryManagement;
    private javax.swing.JTable t_viewSecretaryData;
    private javax.swing.JTextField tf_code;
    private javax.swing.JTextField tf_secretaryName;
    private javax.swing.JTextField tf_secretaryPassword;
    // End of variables declaration//GEN-END:variables

}
