/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static newatomicstudent.functions.*;

/**
 *
 * @author mahmo
 */
public class SystemMonitoring extends javax.swing.JFrame {

    // general_connection with the database
    Connection con;
    DefaultListModel dlm14 = new DefaultListModel();

    /**
     * Creates new form StudentManagement
     */
    public SystemMonitoring() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();
        // connect to the database
        con = admin_connection();
        // set all panels not visible except add panel and make the button add student request focus
        hoverInMouseClicked(btn_systemMonitoring);
        pl_systemMonitoring.setVisible(true);
        
        // set the table auto sorter
        setTableSorter(t_events);
        
        //************************ this for adding panel********************///////
        // change cursor pointer to hand cursor in all buttons;
        changeCurssorWhenEnterButton(btn_Setting);
        changeCurssorWhenEnterButton(btn_systemMonitoring);
        changeCurssorWhenEnterButton(btn_home);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        sp_systemMonitoring = new javax.swing.JScrollPane();
        pl_background = new javax.swing.JPanel();
        pl_topButtonControl = new javax.swing.JPanel();
        lp_empty = new javax.swing.JLabel();
        lp_empty1 = new javax.swing.JLabel();
        lp_empty2 = new javax.swing.JLabel();
        lp_empty4 = new javax.swing.JLabel();
        lp_empty3 = new javax.swing.JLabel();
        btn_systemMonitoring = new javax.swing.JButton();
        systemMonitoring = new javax.swing.JLayeredPane();
        pl_systemMonitoring = new javax.swing.JPanel();
        lb_endDate = new javax.swing.JLabel();
        dc_endDate = new com.toedter.calendar.JDateChooser();
        dc_startDate = new com.toedter.calendar.JDateChooser();
        lb_startDate = new javax.swing.JLabel();
        lb_chooseDate = new javax.swing.JLabel();
        btn_viewGroupAttendance = new javax.swing.JButton();
        btn_delete1 = new javax.swing.JButton();
        sp_events = new javax.swing.JScrollPane();
        t_events = new javax.swing.JTable();
        btn_deleteSelected = new javax.swing.JButton();
        pl_bottomButtonCotrol = new javax.swing.JPanel();
        lb_empty3 = new javax.swing.JLabel();
        lb_empty4 = new javax.swing.JLabel();
        lb_empty5 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_Setting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pl_background.setBackground(new java.awt.Color(255, 255, 255));
        pl_background.setMinimumSize(new java.awt.Dimension(1205, 650));

        pl_topButtonControl.setBackground(new java.awt.Color(19, 64, 93));
        pl_topButtonControl.setMinimumSize(new java.awt.Dimension(1205, 60));
        pl_topButtonControl.setPreferredSize(new java.awt.Dimension(1205, 60));
        pl_topButtonControl.setLayout(new java.awt.GridLayout(1, 0, 10, 10));
        pl_topButtonControl.add(lp_empty);
        pl_topButtonControl.add(lp_empty1);
        pl_topButtonControl.add(lp_empty2);
        pl_topButtonControl.add(lp_empty4);
        pl_topButtonControl.add(lp_empty3);

        btn_systemMonitoring.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_systemMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        btn_systemMonitoring.setText("مراقبة النظام");
        btn_systemMonitoring.setContentAreaFilled(false);
        btn_systemMonitoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_systemMonitoringMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_systemMonitoringMouseExited(evt);
            }
        });
        btn_systemMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_systemMonitoringActionPerformed(evt);
            }
        });
        pl_topButtonControl.add(btn_systemMonitoring);

        systemMonitoring.setPreferredSize(new java.awt.Dimension(1205, 553));
        systemMonitoring.setLayout(new java.awt.CardLayout());

        pl_systemMonitoring.setBackground(new java.awt.Color(255, 255, 255));
        pl_systemMonitoring.setPreferredSize(new java.awt.Dimension(1205, 541));

        lb_endDate.setBackground(new java.awt.Color(255, 255, 255));
        lb_endDate.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        lb_endDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_endDate.setText("الي");

        dc_endDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        dc_endDate.setDateFormatString("yyyy-MM-dd");
        dc_endDate.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        dc_endDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dc_endDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dc_endDateFocusLost(evt);
            }
        });

        dc_startDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        dc_startDate.setDateFormatString("yyyy-MM-dd");
        dc_startDate.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        dc_startDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dc_startDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dc_startDateFocusLost(evt);
            }
        });
        dc_startDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dc_startDateMouseClicked(evt);
            }
        });

        lb_startDate.setBackground(new java.awt.Color(255, 255, 255));
        lb_startDate.setFont(new java.awt.Font("Cairo", 1, 17)); // NOI18N
        lb_startDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_startDate.setText("من");

        lb_chooseDate.setBackground(new java.awt.Color(255, 255, 255));
        lb_chooseDate.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        lb_chooseDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_chooseDate.setText("اختر الفترة");

        btn_viewGroupAttendance.setBackground(new java.awt.Color(19, 64, 93));
        btn_viewGroupAttendance.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_viewGroupAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewGroupAttendance.setText("عرض");
        btn_viewGroupAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewGroupAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewGroupAttendanceMouseExited(evt);
            }
        });
        btn_viewGroupAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewGroupAttendanceActionPerformed(evt);
            }
        });

        btn_delete1.setBackground(new java.awt.Color(153, 0, 0));
        btn_delete1.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_delete1.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete1.setText("حذف الكل");
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });

        t_events.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        t_events.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        t_events.setRowHeight(30);
        t_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_eventsMouseClicked(evt);
            }
        });
        sp_events.setViewportView(t_events);

        btn_deleteSelected.setBackground(new java.awt.Color(153, 0, 0));
        btn_deleteSelected.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_deleteSelected.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteSelected.setText("حذف المختار");
        btn_deleteSelected.setEnabled(false);
        btn_deleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pl_systemMonitoringLayout = new javax.swing.GroupLayout(pl_systemMonitoring);
        pl_systemMonitoring.setLayout(pl_systemMonitoringLayout);
        pl_systemMonitoringLayout.setHorizontalGroup(
            pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_events)
                    .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_chooseDate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pl_systemMonitoringLayout.createSequentialGroup()
                        .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                        .addComponent(btn_deleteSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                        .addComponent(btn_viewGroupAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dc_endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dc_startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_endDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        pl_systemMonitoringLayout.setVerticalGroup(
            pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_chooseDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                        .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pl_systemMonitoringLayout.createSequentialGroup()
                                .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_startDate)
                                    .addComponent(dc_startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pl_systemMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_endDate)
                                    .addComponent(dc_endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_deleteSelected))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_systemMonitoringLayout.createSequentialGroup()
                        .addComponent(btn_viewGroupAttendance)
                        .addGap(37, 37, 37)))
                .addComponent(sp_events, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete1)
                .addGap(18, 18, 18))
        );

        systemMonitoring.add(pl_systemMonitoring, "card7");

        pl_bottomButtonCotrol.setBackground(new java.awt.Color(19, 64, 93));
        pl_bottomButtonCotrol.setMinimumSize(new java.awt.Dimension(1205, 60));
        pl_bottomButtonCotrol.setPreferredSize(new java.awt.Dimension(1205, 60));
        pl_bottomButtonCotrol.setLayout(new java.awt.GridLayout(1, 0, 30, 0));
        pl_bottomButtonCotrol.add(lb_empty3);
        pl_bottomButtonCotrol.add(lb_empty4);
        pl_bottomButtonCotrol.add(lb_empty5);

        btn_home.setBackground(new java.awt.Color(19, 64, 93));
        btn_home.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-btn.png"))); // NOI18N
        btn_home.setText("الرئيسية");
        btn_home.setContentAreaFilled(false);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_home.setIconTextGap(16);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pl_bottomButtonCotrol.add(btn_home);

        btn_Setting.setBackground(new java.awt.Color(19, 64, 93));
        btn_Setting.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_Setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Settings.png"))); // NOI18N
        btn_Setting.setText("الاعدادات");
        btn_Setting.setContentAreaFilled(false);
        btn_Setting.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_Setting.setIconTextGap(16);
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });
        btn_Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SettingActionPerformed(evt);
            }
        });
        pl_bottomButtonCotrol.add(btn_Setting);

        javax.swing.GroupLayout pl_backgroundLayout = new javax.swing.GroupLayout(pl_background);
        pl_background.setLayout(pl_backgroundLayout);
        pl_backgroundLayout.setHorizontalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_topButtonControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(systemMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pl_bottomButtonCotrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pl_backgroundLayout.setVerticalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_backgroundLayout.createSequentialGroup()
                .addComponent(pl_topButtonControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pl_bottomButtonCotrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        sp_systemMonitoring.setViewportView(pl_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_systemMonitoring, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_systemMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // this function will clean after update,delete or clean after search for student
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(returnYourImageURL())));
    }


    private void btn_systemMonitoringMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_systemMonitoringMouseEntered
        if (pl_systemMonitoring.isVisible() == false) {
            hoverInMouseMotion(btn_systemMonitoring);
        }
    }//GEN-LAST:event_btn_systemMonitoringMouseEntered

    private void btn_systemMonitoringMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_systemMonitoringMouseExited
        if (pl_systemMonitoring.isVisible() != true) {
            btn_systemMonitoring.setContentAreaFilled(false);
        }

    }//GEN-LAST:event_btn_systemMonitoringMouseExited

    private void btn_systemMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_systemMonitoringActionPerformed

        // view only add panel  
        pl_systemMonitoring.setVisible(true);

        // hover only add button
        hoverInMouseClicked(btn_systemMonitoring);

    }//GEN-LAST:event_btn_systemMonitoringActionPerformed

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        hoverInMouseMotion(btn_Setting);
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        defaultAfterHover(btn_Setting);
    }//GEN-LAST:event_btn_SettingMouseExited

    private void btn_SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SettingActionPerformed
        this.setVisible(false);
        TeacherSettings teacherSettings = new TeacherSettings();
        if (this.getExtendedState() != 0) {
            teacherSettings.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherSettings.setVisible(true);
    }//GEN-LAST:event_btn_SettingActionPerformed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        hoverInMouseMotion(btn_home);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        defaultAfterHover(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        this.setVisible(false);
        TeacherControl teacherControl = new TeacherControl();
        if (this.getExtendedState() != 0) {
            teacherControl.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherControl.setVisible(true);

    }//GEN-LAST:event_btn_homeActionPerformed

    private void dc_endDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc_endDateFocusGained
        FocusLostOrGained(dc_endDate);
    }//GEN-LAST:event_dc_endDateFocusGained

    private void dc_endDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc_endDateFocusLost
        FocusLostOrGained(dc_endDate);
    }//GEN-LAST:event_dc_endDateFocusLost

    private void dc_startDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc_startDateFocusGained
       
    }//GEN-LAST:event_dc_startDateFocusGained

    private void dc_startDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc_startDateFocusLost
        FocusLostOrGained(dc_startDate);
    }//GEN-LAST:event_dc_startDateFocusLost

    private void t_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_eventsMouseClicked
        btn_deleteSelected.setEnabled(true);
    }//GEN-LAST:event_t_eventsMouseClicked

    private void btn_viewGroupAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewGroupAttendanceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_viewGroupAttendanceMouseEntered

    private void btn_viewGroupAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewGroupAttendanceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_viewGroupAttendanceMouseExited

    private void btn_viewGroupAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewGroupAttendanceActionPerformed
        if (checkEmpty(dc_startDate) && checkEmpty(dc_endDate)) {
            String first_date = ((JTextField) dc_startDate.getDateEditor().getUiComponent()).getText();
            String second_date = ((JTextField) dc_endDate.getDateEditor().getUiComponent()).getText();
            loadSystemView(first_date, second_date, t_events);
        }
    }//GEN-LAST:event_btn_viewGroupAttendanceActionPerformed

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
        if (checkEmpty(dc_startDate) && checkEmpty(dc_endDate)) {
            if (adminAccept()) {
                try {
                    DefaultTableModel dtm = new DefaultTableModel();
                    PreparedStatement stmt = con.prepareStatement("delete from system_monitoring");
                    stmt.execute();
                    deleteMessage();
                    btn_deleteSelected.setEnabled(false);
                    t_events.setModel(dtm);
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            }
        }
    }//GEN-LAST:event_btn_delete1ActionPerformed

    private void btn_deleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSelectedActionPerformed
        if (adminAccept()) {
            String date;
            String time;
            String first_date = ((JTextField) dc_startDate.getDateEditor().getUiComponent()).getText();
            String second_date = ((JTextField) dc_endDate.getDateEditor().getUiComponent()).getText();
            TableModel model1 = t_events.getModel();
            int[] index = t_events.getSelectedRows();
            if (index.length > 0) {
                date = String.valueOf(model1.getValueAt(index[0], 1));
                time = String.valueOf(model1.getValueAt(index[0], 0));
                try {
                    PreparedStatement stmt = con.prepareStatement("delete from system_monitoring where event_date=? and event_time=?");
                    stmt.setString(1, date);
                    stmt.setString(2, time);
                    stmt.execute();
                    deleteMessage();
                    loadSystemView(first_date, second_date, t_events);
                    btn_deleteSelected.setEnabled(false);
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            } else {
                JOptionPane.showMessageDialog(null, "تاكد من اختيار احد الفرق من الجدول");
            }
        }
    }//GEN-LAST:event_btn_deleteSelectedActionPerformed

    private void dc_startDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dc_startDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dc_startDateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemMonitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemMonitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemMonitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemMonitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemMonitoring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Setting;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_deleteSelected;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_systemMonitoring;
    private javax.swing.JButton btn_viewGroupAttendance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dc_endDate;
    private com.toedter.calendar.JDateChooser dc_startDate;
    private javax.swing.JLabel lb_chooseDate;
    private javax.swing.JLabel lb_empty3;
    private javax.swing.JLabel lb_empty4;
    private javax.swing.JLabel lb_empty5;
    private javax.swing.JLabel lb_endDate;
    private javax.swing.JLabel lb_startDate;
    private javax.swing.JLabel lp_empty;
    private javax.swing.JLabel lp_empty1;
    private javax.swing.JLabel lp_empty2;
    private javax.swing.JLabel lp_empty3;
    private javax.swing.JLabel lp_empty4;
    private javax.swing.JPanel pl_background;
    private javax.swing.JPanel pl_bottomButtonCotrol;
    private javax.swing.JPanel pl_systemMonitoring;
    private javax.swing.JPanel pl_topButtonControl;
    private javax.swing.JScrollPane sp_events;
    private javax.swing.JScrollPane sp_systemMonitoring;
    private javax.swing.JLayeredPane systemMonitoring;
    private javax.swing.JTable t_events;
    // End of variables declaration//GEN-END:variables

}
