/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import Login.Login;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static newatomicstudent.functions.*;

/**
 *
 * @author mahmo
 */
public class TeacherProfile extends javax.swing.JFrame {

    Connection adminCon = admin_connection();

    /**
     * Creates new form Login
     */
    public TeacherProfile() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();

        // show the profile panel
        pl_profile.setVisible(true);
        hoverInMouseClicked(btn_profile);

        tf_code.setText(loadHolderCode());
        tf_teacherName.setText(loadHolderName());

        vrai.setVisible(false);
        vrai1.setVisible(false);
        vrai2.setVisible(false);
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(returnYourImageURL())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sp_login = new javax.swing.JScrollPane();
        pl_background = new javax.swing.JPanel();
        pl_login = new javax.swing.JPanel();
        lp_empty1 = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();
        pl_control = new javax.swing.JPanel();
        btn_setting = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        teacherProfile = new javax.swing.JLayeredPane();
        pl_profile = new javax.swing.JPanel();
        pl_teacherData = new javax.swing.JPanel();
        tf_code = new javax.swing.JTextField();
        lb_code = new javax.swing.JLabel();
        tf_teacherName = new javax.swing.JTextField();
        lb_teacherName = new javax.swing.JLabel();
        pl_passwordData = new javax.swing.JPanel();
        tf_oldTeacherPassword = new javax.swing.JTextField();
        lb_teacherPassword1 = new javax.swing.JLabel();
        tf_newTeacherPassword = new javax.swing.JTextField();
        lb_teacherPassword2 = new javax.swing.JLabel();
        tf_confirmTeacherPassword = new javax.swing.JTextField();
        lb_teacherPassword3 = new javax.swing.JLabel();
        btn_updatePassword = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        pl_horizontalBottomLine1 = new javax.swing.JPanel();
        pl_deleteCodeData1 = new javax.swing.JPanel();
        tf_oldAcceptanceCode = new javax.swing.JTextField();
        lb_code2 = new javax.swing.JLabel();
        tf_newAcceptanceCode = new javax.swing.JTextField();
        lb_code3 = new javax.swing.JLabel();
        pl_horizontalBottomLine2 = new javax.swing.JPanel();
        btn_updateAcceptanceCode = new javax.swing.JButton();
        vrai1 = new javax.swing.JLabel();
        vrai = new javax.swing.JLabel();
        vrai2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sp_login.setBackground(new java.awt.Color(255, 255, 255));

        pl_background.setBackground(new java.awt.Color(255, 255, 255));

        pl_login.setBackground(new java.awt.Color(19, 64, 93));
        pl_login.setPreferredSize(new java.awt.Dimension(702, 600));
        pl_login.setLayout(new java.awt.GridLayout(10, 0, 0, 15));
        pl_login.add(lp_empty1);

        btn_profile.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setText("الصفحة الشخصية");
        btn_profile.setContentAreaFilled(false);
        btn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_profileMouseExited(evt);
            }
        });
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });
        pl_login.add(btn_profile);

        pl_control.setBackground(new java.awt.Color(19, 64, 93));
        pl_control.setPreferredSize(new java.awt.Dimension(702, 600));
        pl_control.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btn_setting.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile setting.png"))); // NOI18N
        btn_setting.setContentAreaFilled(false);
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_settingMouseExited(evt);
            }
        });
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });
        pl_control.add(btn_setting);

        btn_home.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile home.png"))); // NOI18N
        btn_home.setContentAreaFilled(false);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pl_control.add(btn_home);

        btn_logout.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/profile logout.png"))); // NOI18N
        btn_logout.setContentAreaFilled(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pl_control.add(btn_logout);

        teacherProfile.setLayout(new java.awt.CardLayout());

        pl_profile.setBackground(new java.awt.Color(255, 255, 255));

        pl_teacherData.setBackground(new java.awt.Color(255, 255, 255));
        pl_teacherData.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        tf_code.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_code.setToolTipText("اكتب كود الطالب و تاكد من ان يكون رقم صحيح");
        tf_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_code.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_code.setDoubleBuffered(true);
        tf_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codeFocusLost(evt);
            }
        });
        tf_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeKeyPressed(evt);
            }
        });
        pl_teacherData.add(tf_code);

        lb_code.setBackground(new java.awt.Color(255, 255, 255));
        lb_code.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_code.setText("كود المالك");
        pl_teacherData.add(lb_code);

        tf_teacherName.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_teacherName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_teacherName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_teacherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_teacherNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_teacherNameFocusLost(evt);
            }
        });
        tf_teacherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_teacherNameKeyPressed(evt);
            }
        });
        pl_teacherData.add(tf_teacherName);

        lb_teacherName.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherName.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherName.setText("اسم المالك");
        pl_teacherData.add(lb_teacherName);

        pl_passwordData.setBackground(new java.awt.Color(255, 255, 255));
        pl_passwordData.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        tf_oldTeacherPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_oldTeacherPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_oldTeacherPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_oldTeacherPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_oldTeacherPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_oldTeacherPasswordFocusLost(evt);
            }
        });
        tf_oldTeacherPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_oldTeacherPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_oldTeacherPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_oldTeacherPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_oldTeacherPassword);

        lb_teacherPassword1.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword1.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword1.setText("كلمة المرور الحالية");
        pl_passwordData.add(lb_teacherPassword1);

        tf_newTeacherPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_newTeacherPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_newTeacherPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_newTeacherPassword.setEnabled(false);
        tf_newTeacherPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_newTeacherPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_newTeacherPasswordFocusLost(evt);
            }
        });
        tf_newTeacherPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_newTeacherPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_newTeacherPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_newTeacherPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_newTeacherPassword);

        lb_teacherPassword2.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword2.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword2.setText("كلمة المرور الجديدة");
        pl_passwordData.add(lb_teacherPassword2);

        tf_confirmTeacherPassword.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_confirmTeacherPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_confirmTeacherPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_confirmTeacherPassword.setEnabled(false);
        tf_confirmTeacherPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_confirmTeacherPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_confirmTeacherPasswordFocusLost(evt);
            }
        });
        tf_confirmTeacherPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_confirmTeacherPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_confirmTeacherPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_confirmTeacherPasswordKeyTyped(evt);
            }
        });
        pl_passwordData.add(tf_confirmTeacherPassword);

        lb_teacherPassword3.setBackground(new java.awt.Color(255, 255, 255));
        lb_teacherPassword3.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_teacherPassword3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_teacherPassword3.setText("تاكيد كلمة المرور الجديدة");
        pl_passwordData.add(lb_teacherPassword3);

        btn_updatePassword.setBackground(new java.awt.Color(0, 155, 255));
        btn_updatePassword.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_updatePassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_updatePassword.setText("تغيير كلمة المرور");
        btn_updatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatePasswordActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(21, 145, 95));
        btn_save.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("حفظ");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        pl_horizontalBottomLine1.setBackground(new java.awt.Color(102, 102, 102));
        pl_horizontalBottomLine1.setMinimumSize(new java.awt.Dimension(440, 5));
        pl_horizontalBottomLine1.setPreferredSize(new java.awt.Dimension(800, 2));

        javax.swing.GroupLayout pl_horizontalBottomLine1Layout = new javax.swing.GroupLayout(pl_horizontalBottomLine1);
        pl_horizontalBottomLine1.setLayout(pl_horizontalBottomLine1Layout);
        pl_horizontalBottomLine1Layout.setHorizontalGroup(
            pl_horizontalBottomLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pl_horizontalBottomLine1Layout.setVerticalGroup(
            pl_horizontalBottomLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pl_deleteCodeData1.setBackground(new java.awt.Color(255, 255, 255));
        pl_deleteCodeData1.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        tf_oldAcceptanceCode.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_oldAcceptanceCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_oldAcceptanceCode.setToolTipText("");
        tf_oldAcceptanceCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_oldAcceptanceCode.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_oldAcceptanceCode.setDoubleBuffered(true);
        tf_oldAcceptanceCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_oldAcceptanceCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_oldAcceptanceCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_oldAcceptanceCodeKeyTyped(evt);
            }
        });
        pl_deleteCodeData1.add(tf_oldAcceptanceCode);

        lb_code2.setBackground(new java.awt.Color(255, 255, 255));
        lb_code2.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_code2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_code2.setText("كود الموافقة القديم");
        pl_deleteCodeData1.add(lb_code2);

        tf_newAcceptanceCode.setFont(new java.awt.Font("Cairo", 1, 14)); // NOI18N
        tf_newAcceptanceCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_newAcceptanceCode.setToolTipText("اكتب كود الطالب و تاكد من ان يكون رقم صحيح");
        tf_newAcceptanceCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 255), 2, true));
        tf_newAcceptanceCode.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_newAcceptanceCode.setDoubleBuffered(true);
        tf_newAcceptanceCode.setEnabled(false);
        tf_newAcceptanceCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_newAcceptanceCodeKeyPressed(evt);
            }
        });
        pl_deleteCodeData1.add(tf_newAcceptanceCode);

        lb_code3.setBackground(new java.awt.Color(255, 255, 255));
        lb_code3.setFont(new java.awt.Font("Cairo", 1, 20)); // NOI18N
        lb_code3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_code3.setText("كود الموافقة الجديد");
        pl_deleteCodeData1.add(lb_code3);

        pl_horizontalBottomLine2.setBackground(new java.awt.Color(102, 102, 102));
        pl_horizontalBottomLine2.setMinimumSize(new java.awt.Dimension(440, 5));
        pl_horizontalBottomLine2.setPreferredSize(new java.awt.Dimension(800, 2));

        javax.swing.GroupLayout pl_horizontalBottomLine2Layout = new javax.swing.GroupLayout(pl_horizontalBottomLine2);
        pl_horizontalBottomLine2.setLayout(pl_horizontalBottomLine2Layout);
        pl_horizontalBottomLine2Layout.setHorizontalGroup(
            pl_horizontalBottomLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pl_horizontalBottomLine2Layout.setVerticalGroup(
            pl_horizontalBottomLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_updateAcceptanceCode.setBackground(new java.awt.Color(153, 0, 0));
        btn_updateAcceptanceCode.setFont(new java.awt.Font("Cairo", 1, 18)); // NOI18N
        btn_updateAcceptanceCode.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateAcceptanceCode.setText("تغيير كود المسح");
        btn_updateAcceptanceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateAcceptanceCodeActionPerformed(evt);
            }
        });

        vrai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/vrai.png"))); // NOI18N

        vrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/vrai.png"))); // NOI18N

        vrai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/vrai.png"))); // NOI18N

        javax.swing.GroupLayout pl_profileLayout = new javax.swing.GroupLayout(pl_profile);
        pl_profile.setLayout(pl_profileLayout);
        pl_profileLayout.setHorizontalGroup(
            pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_profileLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pl_profileLayout.createSequentialGroup()
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(pl_teacherData, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pl_profileLayout.createSequentialGroup()
                                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vrai)
                                    .addComponent(vrai1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pl_passwordData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addComponent(pl_horizontalBottomLine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addComponent(btn_updatePassword)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addComponent(vrai2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pl_deleteCodeData1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(pl_horizontalBottomLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addComponent(btn_updateAcceptanceCode)
                        .addGap(194, 194, 194))))
        );
        pl_profileLayout.setVerticalGroup(
            pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_profileLayout.createSequentialGroup()
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_profileLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(pl_teacherData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_profileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_save)
                        .addGap(54, 54, 54)))
                .addComponent(pl_horizontalBottomLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pl_passwordData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pl_profileLayout.createSequentialGroup()
                        .addComponent(vrai1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vrai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(btn_updatePassword)
                .addGap(38, 38, 38)
                .addComponent(pl_horizontalBottomLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pl_deleteCodeData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrai2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_updateAcceptanceCode)
                .addContainerGap())
        );

        teacherProfile.add(pl_profile, "card2");

        javax.swing.GroupLayout pl_backgroundLayout = new javax.swing.GroupLayout(pl_background);
        pl_background.setLayout(pl_backgroundLayout);
        pl_backgroundLayout.setHorizontalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_backgroundLayout.createSequentialGroup()
                .addGroup(pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_backgroundLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(pl_control, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(316, 316, 316))
                    .addComponent(teacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pl_login, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pl_backgroundLayout.setVerticalGroup(
            pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_backgroundLayout.createSequentialGroup()
                .addGroup(pl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_backgroundLayout.createSequentialGroup()
                        .addComponent(pl_control, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherProfile))
                    .addComponent(pl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        sp_login.setViewportView(pl_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sp_login, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseEntered
        if (pl_profile.isVisible() != true) {
            hoverInMouseMotion(btn_profile);
        }
    }//GEN-LAST:event_btn_profileMouseEntered

    private void btn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseExited
        if (pl_profile.isVisible() != true) {
            defaultAfterHover(btn_profile);
        }
    }//GEN-LAST:event_btn_profileMouseExited

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        pl_profile.setVisible(true);
        hoverInMouseClicked(btn_profile);
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseEntered
        hoverInMouseMotion(btn_setting);
    }//GEN-LAST:event_btn_settingMouseEntered

    private void btn_settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseExited
        defaultAfterHover(btn_setting);
    }//GEN-LAST:event_btn_settingMouseExited

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        this.setVisible(false);
        TeacherSettings teacherSettings = new TeacherSettings();
        if (this.getExtendedState() != 0) {
            teacherSettings.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherSettings.setVisible(true);
    }//GEN-LAST:event_btn_settingActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        this.setVisible(false);
        TeacherControl teacherControl = new TeacherControl();
        if (this.getExtendedState() != 0) {
            teacherControl.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        teacherControl.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        hoverInMouseMotion(btn_logout);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        defaultAfterHover(btn_logout);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تسجيل الخروج", "استفهام", JOptionPane.YES_NO_OPTION, 1);
        if (yes == JOptionPane.YES_OPTION) {
            Login l = new Login();
            this.setVisible(false);
            l.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void tf_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusGained
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusGained

    private void tf_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codeFocusLost
        FocusLostOrGained(tf_code);
    }//GEN-LAST:event_tf_codeFocusLost

    private void tf_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_teacherName.requestFocus(true);
        }
    }//GEN-LAST:event_tf_codeKeyPressed

    private void tf_teacherNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_teacherNameFocusGained
        FocusLostOrGained(tf_teacherName);
    }//GEN-LAST:event_tf_teacherNameFocusGained

    private void tf_teacherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_teacherNameFocusLost
        FocusLostOrGained(tf_teacherName);
    }//GEN-LAST:event_tf_teacherNameFocusLost

    private void tf_teacherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_teacherNameKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_oldTeacherPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_teacherNameKeyPressed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        hoverInMouseMotion(btn_home);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        defaultAfterHover(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_updatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatePasswordActionPerformed
        // check that the important field isn't empty
        int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تغيير كلمة المرور ", "استفهام", JOptionPane.YES_NO_OPTION, 1);
        if (yes == JOptionPane.YES_OPTION) {
            if (checkEmpty(tf_oldTeacherPassword) && checkEmpty(tf_newTeacherPassword) && checkEmpty(tf_confirmTeacherPassword)) {
                String admin_code = loadHolderCode();
                String admin_name = loadHolderName();
                String currentPassword = tf_oldTeacherPassword.getText();
                String newPassword = tf_newTeacherPassword.getText();
                String confrimationPassword = tf_confirmTeacherPassword.getText();
                PreparedStatement stmt;
                if (currentPassword.equals(loadHolderPassword())) {
                    if (newPassword.equals(confrimationPassword)) {
                        try {
                            stmt = adminCon.prepareStatement("update admin set  admin_password=? where admin_code=?");
                            stmt.setString(1, newPassword);
                            stmt.setString(2, admin_code);
                            stmt.execute();
                            updateMessage();
                            updateHolder(admin_code, admin_name, newPassword);
                            cleanAfterUpdatePassword();
                        } catch (SQLException ex) {
                            handleSqlExceptions(ex.getErrorCode());
                        }
                    } else {
                        makeRed(tf_confirmTeacherPassword);
                        jOptionPaneMessage("كلمة المرور الجديده غير مطابقة", 0);
                    }
                } else {
                    makeRed(tf_oldTeacherPassword);
                    jOptionPaneMessage("غير مطابق لكلمة المرور الحالية", 0);
                }

            }
        }
    }//GEN-LAST:event_btn_updatePasswordActionPerformed

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveMouseExited

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        int yes = JOptionPane.showConfirmDialog(null, "هل انت متاكد من انك تريد تغيير الكود و الاسم ", "استفهام", JOptionPane.YES_NO_OPTION, 1);
        if (yes == JOptionPane.YES_OPTION) {
            if (checkEmpty(tf_code) && checkEmpty(tf_teacherName)) {
                String admin_code = tf_code.getText();
                String admin_name = tf_teacherName.getText();
                PreparedStatement stmt;
                try {
                    stmt = adminCon.prepareStatement("update admin set admin_code=?,admin_name=?, admin_password=? where admin_code=?");
                    stmt.setString(1, admin_code);
                    stmt.setString(2, admin_name);
                    stmt.setString(3, loadHolderPassword());
                    stmt.setString(4, loadHolderCode());
                    stmt.execute();
                    updateMessage();
                    updateHolder(admin_code, admin_name, loadHolderPassword());
                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateAcceptanceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateAcceptanceCodeActionPerformed
        if (tf_newAcceptanceCode.isEnabled()) {
            PreparedStatement stmt;
            String deleteCode = tf_newAcceptanceCode.getText();
            try {
                stmt = adminCon.prepareStatement("update adminPermision set accept_code=?");
                stmt.setString(1, deleteCode);
                stmt.execute();
                updateMessage();
                tf_newAcceptanceCode.setText("");
                tf_oldAcceptanceCode.setText("");
                tf_newAcceptanceCode.setEnabled(false);
                vrai2.setVisible(false);
            } catch (SQLException ex) {
                handleSqlExceptions(ex.getErrorCode());
            }
        } else {
            jOptionPaneMessage("تاكد من كتابة كود المسح بطريقة صحيحة", 0);
        }
    }//GEN-LAST:event_btn_updateAcceptanceCodeActionPerformed

    private void tf_confirmTeacherPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmTeacherPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_confirmTeacherPasswordKeyPressed

    private void tf_confirmTeacherPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_confirmTeacherPasswordFocusLost
        FocusLostOrGained(tf_confirmTeacherPassword);
    }//GEN-LAST:event_tf_confirmTeacherPasswordFocusLost

    private void tf_confirmTeacherPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_confirmTeacherPasswordFocusGained
        FocusLostOrGained(tf_confirmTeacherPassword);
    }//GEN-LAST:event_tf_confirmTeacherPasswordFocusGained

    private void tf_newTeacherPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newTeacherPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_confirmTeacherPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_newTeacherPasswordKeyPressed

    private void tf_newTeacherPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_newTeacherPasswordFocusLost
        FocusLostOrGained(tf_newTeacherPassword);
    }//GEN-LAST:event_tf_newTeacherPasswordFocusLost

    private void tf_newTeacherPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_newTeacherPasswordFocusGained
        FocusLostOrGained(tf_newTeacherPassword);
    }//GEN-LAST:event_tf_newTeacherPasswordFocusGained

    private void tf_oldTeacherPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldTeacherPasswordKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_newTeacherPassword.requestFocus(true);
        }
    }//GEN-LAST:event_tf_oldTeacherPasswordKeyPressed

    private void tf_oldTeacherPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_oldTeacherPasswordFocusLost
        FocusLostOrGained(tf_oldTeacherPassword);
    }//GEN-LAST:event_tf_oldTeacherPasswordFocusLost

    private void tf_oldTeacherPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_oldTeacherPasswordFocusGained
        FocusLostOrGained(tf_oldTeacherPassword);
    }//GEN-LAST:event_tf_oldTeacherPasswordFocusGained

    private void tf_oldTeacherPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldTeacherPasswordKeyTyped
        if (tf_oldTeacherPassword.getText().equals(loadHolderPassword())) {
            vrai1.setVisible(true);
            tf_newTeacherPassword.setEnabled(true);
            tf_confirmTeacherPassword.setEnabled(true);
            vrai.setVisible(true);
        } else {
            vrai1.setVisible(false);
            tf_newTeacherPassword.setEnabled(false);
            tf_confirmTeacherPassword.setEnabled(false);
            vrai1.setVisible(false);
        }
    }//GEN-LAST:event_tf_oldTeacherPasswordKeyTyped

    private void tf_oldTeacherPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldTeacherPasswordKeyReleased
        if (tf_oldTeacherPassword.getText().equals(loadHolderPassword())) {
            vrai1.setVisible(true);
            tf_newTeacherPassword.setEnabled(true);
            tf_confirmTeacherPassword.setEnabled(true);
        } else {
            vrai.setVisible(false);
            tf_newTeacherPassword.setEnabled(false);
            tf_confirmTeacherPassword.setEnabled(false);
            vrai1.setVisible(false);
        }

    }//GEN-LAST:event_tf_oldTeacherPasswordKeyReleased

    private void tf_newTeacherPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newTeacherPasswordKeyReleased
        if (tf_confirmTeacherPassword.getText().equals(tf_newTeacherPassword.getText()) && !tf_newTeacherPassword.getText().equals("") && !tf_confirmTeacherPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_newTeacherPasswordKeyReleased

    private void tf_newTeacherPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newTeacherPasswordKeyTyped
        if (tf_confirmTeacherPassword.getText().equals(tf_newTeacherPassword.getText()) && !tf_newTeacherPassword.getText().equals("") && !tf_confirmTeacherPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_newTeacherPasswordKeyTyped

    private void tf_confirmTeacherPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmTeacherPasswordKeyReleased
        if (tf_confirmTeacherPassword.getText().equals(tf_newTeacherPassword.getText()) && !tf_newTeacherPassword.getText().equals("") && !tf_confirmTeacherPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_confirmTeacherPasswordKeyReleased

    private void tf_confirmTeacherPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_confirmTeacherPasswordKeyTyped
        if (tf_confirmTeacherPassword.getText().equals(tf_newTeacherPassword.getText()) && !tf_newTeacherPassword.getText().equals("") && !tf_confirmTeacherPassword.getText().equals("")) {
            vrai.setVisible(true);
        } else {
            vrai.setVisible(false);
        }
    }//GEN-LAST:event_tf_confirmTeacherPasswordKeyTyped

    private void tf_oldAcceptanceCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldAcceptanceCodeKeyTyped
        if (tf_oldAcceptanceCode.getText().equals(returnAcceptCode())) {
            tf_newAcceptanceCode.setEnabled(true);
            vrai2.setVisible(true);
        } else {
            tf_newAcceptanceCode.setEnabled(false);
            vrai2.setVisible(false);
        }
    }//GEN-LAST:event_tf_oldAcceptanceCodeKeyTyped

    private void tf_oldAcceptanceCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldAcceptanceCodeKeyPressed
        if (enter(evt.getKeyChar())) {
            tf_newAcceptanceCode.requestFocus(true);
        }
    }//GEN-LAST:event_tf_oldAcceptanceCodeKeyPressed

    private void tf_oldAcceptanceCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_oldAcceptanceCodeKeyReleased
        if (tf_oldAcceptanceCode.getText().equals(returnAcceptCode())) {
            tf_newAcceptanceCode.setEnabled(true);
            vrai2.setVisible(true);
        } else {
            tf_newAcceptanceCode.setEnabled(false);
            vrai2.setVisible(false);
        }
    }//GEN-LAST:event_tf_oldAcceptanceCodeKeyReleased

    private void tf_newAcceptanceCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_newAcceptanceCodeKeyPressed
        if (enter(evt.getKeyChar())) {
            if (tf_newAcceptanceCode.isEnabled()) {
                PreparedStatement stmt;
                String deleteCode = tf_newAcceptanceCode.getText();
                try {
                    stmt = adminCon.prepareStatement("update adminPermision set accept_code=?");
                    stmt.setString(1, deleteCode);
                    stmt.execute();
                    updateMessage();
                    tf_newAcceptanceCode.setText("");
                    tf_oldAcceptanceCode.setText("");
                    tf_newAcceptanceCode.setEnabled(false);
                    vrai2.setVisible(false);

                } catch (SQLException ex) {
                    handleSqlExceptions(ex.getErrorCode());
                }
            } else {
                jOptionPaneMessage("تاكد من كتابة كود المسح بطريقة صحيحة", 0);
            }
        }
    }//GEN-LAST:event_tf_newAcceptanceCodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_updateAcceptanceCode;
    private javax.swing.JButton btn_updatePassword;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_code2;
    private javax.swing.JLabel lb_code3;
    private javax.swing.JLabel lb_teacherName;
    private javax.swing.JLabel lb_teacherPassword1;
    private javax.swing.JLabel lb_teacherPassword2;
    private javax.swing.JLabel lb_teacherPassword3;
    private javax.swing.JLabel lp_empty1;
    private javax.swing.JPanel pl_background;
    private javax.swing.JPanel pl_control;
    private javax.swing.JPanel pl_deleteCodeData1;
    private javax.swing.JPanel pl_horizontalBottomLine1;
    private javax.swing.JPanel pl_horizontalBottomLine2;
    private javax.swing.JPanel pl_login;
    private javax.swing.JPanel pl_passwordData;
    private javax.swing.JPanel pl_profile;
    private javax.swing.JPanel pl_teacherData;
    private javax.swing.JScrollPane sp_login;
    private javax.swing.JLayeredPane teacherProfile;
    private javax.swing.JTextField tf_code;
    private javax.swing.JTextField tf_confirmTeacherPassword;
    private javax.swing.JTextField tf_newAcceptanceCode;
    private javax.swing.JTextField tf_newTeacherPassword;
    private javax.swing.JTextField tf_oldAcceptanceCode;
    private javax.swing.JTextField tf_oldTeacherPassword;
    private javax.swing.JTextField tf_teacherName;
    private javax.swing.JLabel vrai;
    private javax.swing.JLabel vrai1;
    private javax.swing.JLabel vrai2;
    // End of variables declaration//GEN-END:variables

    private void cleanAfterUpdatePassword() {
        tf_oldTeacherPassword.setText("");
        tf_newTeacherPassword.setText("");
        tf_confirmTeacherPassword.setText("");
        FocusLostOrGained(tf_oldTeacherPassword);
        FocusLostOrGained(tf_newTeacherPassword);
        FocusLostOrGained(tf_confirmTeacherPassword);
    }
}
